### ISSUE TITLE
running in distributed mode and cp 4.0.0

### ISSUE THREAD

**Issue by natb1** [wepay/kafka-connect-bigquery#106]
Does anybody have this running successfully with a distributed connect worker?

I have a standalone worker successfully loading data into my BQ table. When I try to do the same with a distributed worker I get the following exception:
```
ERROR WorkerSinkTask{id=...} Commit of offsets threw an unexpected exception for sequence number 1: null (org.apache.kafka.connect.runtime.WorkerSinkTask:233)
java.lang.ClassCastException: org.apache.kafka.clients.consumer.OffsetAndMetadata cannot be cast to org.apache.kafka.clients.consumer.OffsetAndMetadata
at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.updateOffsets(BigQuerySinkTask.java:112)
at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.flush(BigQuerySinkTask.java:101)
at org.apache.kafka.connect.sink.SinkTask.preCommit(SinkTask.java:117)
```
This seems like some sort of version mismatch issue, though I have tried it with confluent platform 3.0.0 as referenced in the docs, as well as the newer 4.0.0-3.

Any pointers on getting this running in distributed mode or dealing with these versioning issues in general?

**Comment by criccomini** [comment]
We are running in distributed mode. We have not yet tried to run with CP 4.0, but we will be shortly (in next week or two). @mtagle ever seen anything like this?

**Comment by criccomini** [comment]
@natb1 have a look at the tail end of this discussion:
https://github.com/confluentinc/kafka-connect-storage-cloud/issues/76

**Comment by criccomini** [comment]
@natb1 one general recommendation (that is NOT the way we run it, but was recommended to me recently by some folks) is to actually run in local mode in wrapped in k8s. That would give you auto-restart if the pod fails, while keeping you away from some of the complexity of distributed mode.

Just 2c. That said, we should still figure out why this is happening.

**Comment by criccomini** [comment]
```
org.apache.kafka.clients.consumer.OffsetAndMetadata cannot be cast to org.apache.kafka.clients.consumer.OffsetAndMetadata
```
This seems like a classpath issue. Is it possible that you have different versions of Kafka in your classpath?

**Comment by criccomini** [comment]
Yup. https://groups.google.com/forum/#!topic/confluent-platform/cmg-4qJH9YE

Recommend you have a look at the Kafka connect version number and make sure it looks EXACTLY the same as what KCBQ is using. Double check classpaths, etc.

Also, I believe they added the ability to have custom class loaders to get around this issue in Kafka connect, so it might be worth digging into that feature to see if it suits your needs.

**Comment by natb1** [comment]
Ok, so it sounds like loading this through `plugin.path` like I am trying to do is probably what's creating classpath issues (as opposed to when I run in standalone mode and explicitly set the CLASSPATH environment variable).

**Comment by criccomini** [comment]
Yea, if you're using the new classloader stuff (sounds like you are since plugin.path is part of the KIP), then we haven't tried that yet. It SHOULD work, but 1) that's a new feature 2) I haven't tried it yet.

All that said, if you continue digging, would love to hear what the issue is. If it requires a patch, PRs welcome, and happy to help.

**Comment by natb1** [comment]
ya, I can't pinpoint what my exact issue was, but I have it working now. Thanks for helping me walk through it. I'll follow up with my exact config for anybody else trying to get distributed workers running in cp 4.0.0

**Comment by criccomini** [comment]
👍

**Comment by natb1** [comment]
Here's my Dockerfile:
```
FROM confluentinc/cp-kafka-connect:4.0.0-3 AS base

FROM base AS build
COPY ./kafka-connect-bigquery /kafka-connect-bigquery
RUN cd /kafka-connect-bigquery \
    && ./gradlew clean confluentTarBall
RUN mkdir -p /usr/local/share/kafka/plugins
RUN tar -C /usr/local/share/kafka/plugins -xvf /kafka-connect-bigquery/bin/tar/kcbq-connector-*-confluent-dist.tar

FROM base AS release
COPY --from=build /usr/local/share/kafka/plugins /usr/local/share/kafka/plugins
```
In my conf:
```
    plugin.path=/usr/share/java,/usr/local/share/kafka/plugins
```
My env:
```
        command: 
        - connect-distributed
        - /kafka-config/distributed.properties
        env:
        - name: CLASSPATH
          value: "/usr/local/share/kafka/plugins/*"
```
My repo is an amalgamation of @cerber's fork who had already done some work on upgrading the libs (though it looks like @trueanthen has done some work on this as well) and #100 . Sorry I don't have a free moment to parse out how much of that is actually necessary, but I hope this helps.

**Comment by geopamplona** [comment]
i have same error on 4.1.0 version

sometimes connector fail and sometimes conector is ok

I do not know how to reproduce the error

```
-05-16 12:35:47,811] ERROR WorkerSinkTask{id=sink-connector-0} Offset commit failed, rewinding to last committed offsets (org.apache.kafka.connect.runtime.WorkerSinkTask)
> 16/5/2019 14:35:47java.lang.ClassCastException: org.apache.kafka.clients.consumer.OffsetAndMetadata cannot be cast to org.apache.kafka.clients.consumer.OffsetAndMetadata
> 16/5/2019 14:35:47	at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.updateOffsets(BigQuerySinkTask.java:137)
> 16/5/2019 14:35:47	at com.wepay.kafka.connect.bigquery.BigQuerySinkTask.flush(BigQuerySinkTask.java:126)
> 16/5/2019 14:35:47	at org.apache.kafka.connect.sink.SinkTask.preCommit(SinkTask.java:117)
> 16/5/2019 14:35:47	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:345)
> 16/5/2019 14:35:47	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:182)
> 16/5/2019 14:35:47	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
> 16/5/2019 14:35:47	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
> 16/5/2019 14:35:47	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
> 16/5/2019 14:35:47	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 16/5/2019 14:35:47	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 16/5/2019 14:35:47	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 16/5/2019 14:35:47	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 16/5/2019 14:35:47	at 
```
