### ISSUE TITLE
connector.sh throws "Failed to find any class that implements Connector"

### ISSUE THREAD

**Issue by machieltreffers** [wepay/kafka-connect-bigquery#109]
When running "connector.sh" it stops throwing following error:

`ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:108)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches com.wepay.kafka.connect.bigquery.BigQuerySinkConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='1.0.0-cp1', encodedVersion=1.0.0-cp1, type=source, typeName='source', location='classpath'}
        at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:79)
        at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:66)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:105)`

I've installed Confluent Kafka V4.0 to /usr/bin

I've added kafka-connect-bigquery jars to /usr/share/java/kafka-connect-bigquery/ and added this directory to variables CLASSPATH and CONNECT_PLUGIN_PATH.

As I'm new to Kafka (Connect) I'm afraid I'm overlooking something simple..

**Comment by machieltreffers** [comment]
@mtagle thanks for your reply.

Running env returns:
 `CLASSPATH=/usr/share/java/kafka-connect-bigquery:/usr/share/java`
and 
`CONFLUENT_DIR=/usr`

/usr/share/java/kafka-connect-bigquery contains the kcbq jars

I'm running connector.sh from: /opt/kafka-connect-bigquery-1.0.0/kcbq-connector/quickstart
connector.sh is using: ./properties/standalone.properties and ./properties/connector.properties

Maybe I'm mixing up directories? Shouldn't I've moved the JARs?

**Comment by mtagle** [comment]
try adding a * onto the end of your classpath, like in the page I linked.

Beyond that, I'm not sure what to say. It seems like you could get more help talking to kafka-connect folks than us.

**Comment by machieltreffers** [comment]
Using the connect-standalone.properties file instead of delivered standalone.properties file solved this issue for me. Thank you for your input @mtagle

**Comment by milanj-1** [comment]
I am facing the same error.
The link given by @mtagle (https://docs.confluent.io/3.1.1/connect/userguide.html#installing-connector-plugins) is not working
Can you please provide with some new link which will help to set up the class path? / or any other way to resolve this error

**Comment by milanj-1** [comment]
@machieltreffers Can you please tell where to find the connect-standalone.properties ?
