### ISSUE TITLE
Deserialization exception: Unknown magic byte!

### ISSUE THREAD

**Issue by jeroenr** [wepay/kafka-connect-bigquery#114]
Hi, I'm using version 1.1.0 of this connector and I'm trying to export some data from a Kafka topic to Google Big Query. I verified that I have a correct schema in my schema registry and that I can consume using the kafka-avro-console-consumer (from Confluent platform).

When starting the connector, however, I'm getting the following exceptions in the log: 
`Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!`

The table is created in BigQuery and the fields look correct, but no rows are being written as a result of the exception. 

Any pointers?

**Comment by DediBar** [comment]
same issue

**Comment by criccomini** [comment]
What serialization format are you guys using in the input Kafka topics? Are you producing messages using the Confluent schema registry avro encoder?

https://github.com/confluentinc/schema-registry/blob/master/docs/serializer-formatter.rst
https://github.com/confluentinc/schema-registry/blob/master/avro-serde/src/main/java/io/confluent/kafka/streams/serdes/avro/GenericAvroSerde.java

If so, you should not be seeing this error.

**Comment by DediBar** [comment]
Well I left it default as NUL
Where cat I found example for kafka-connect-bigquery configuration + topic example

**Comment by criccomini** [comment]
@DediBar I don't follow. What is the data in your Kafka topic serialized as?

**Comment by DediBar** [comment]
@criccomini  

I follow the confluent demo https://docs.confluent.io/current/tutorials/cp-demo/docs/index.html#cp-demo

I have 2 topics 

1. pageviews => CSV

$ <path-to-confluent>/bin/ksql-datagen quickstart=pageviews format=delimited topic=pageviews maxInterval=100 \
  propertiesFile=<path-to-confluent>/etc/ksql/datagen.properties

2. Users => JSON 
<path-to-confluent>/bin/ksql-datagen quickstart=users format=json topic=users maxInterval=1000 \
  propertiesFile=<path-to-confluent>/etc/ksql/datagen.properties


I want to use the auto create table but do not know how - well I did not succeed.
I am searching for the configuration of bigquery connector for both TOPICS.

Thank you

**Comment by criccomini** [comment]
@DediBar KCBQ currently works out of the box with Avro topics, not CSV/JSON topics. The reason for this is that we have to map from incoming message schemas to BigQuery schemas (e.g. from Avro schema to BigQuery schema). We have made this mapper pluggable, but we only support Avro out of the box. If you want to use JSON/CSV input rather than Avro input, you'll have to write your own.

https://github.com/wepay/kafka-connect-bigquery/blob/master/kcbq-api/src/main/java/com/wepay/kafka/connect/bigquery/api/SchemaRetriever.java

**Comment by parthdesai21google** [comment]
Hi, I am getting the same error. I converted a JSON file into an AVRO file.
