### ISSUE TITLE
How to implement delete in Kafka Connect BigQuery

### ISSUE THREAD

**Issue by mukund26** [wepay/kafka-connect-bigquery#127]
When I delete data or row in my postgres db, the bigquery connector only reads the after as null and writes null  in my BigQuery Database. Is there a class that is used to delete a row.

**Comment by criccomini** [comment]
BQ does not really support DELETEs. It mostly an append-only DB. You can technically run DELETE commands, but what it does under the hood is simply execute a SELECT * that excludes the deleted rows, stores it in a temp table, then overwrites the source table with the temp table (thus the DELETEd rows disappear).

The way we handle deletes is by putting a view on top of the base table that filters out all rows where the most recent update was a NULL `after` (delete).
