### ISSUE TITLE
Reconcile bufferSize and maxWriteSize in KC BQ

### ISSUE THREAD

**Issue by C0urante** [wepay/kafka-connect-bigquery#15]
(Migrated from internal Jira issue DI-447)

The bufferSize config is currently per-task. The maxWriteSize config is currently per-worker. If I have 10 tasks (tasks.max=10) and:
```plain
bufferSize=100000
maxWriteSize=50000
```
I get writes to BQ that are partitioned into chunks of 5000, but each task's buffer has 100000+ elements in it. This is really confusing. The problem is in BigQuerySinkConnector:
```plain
int maxWritePerTask = config.getInt(config.MAX_WRITE_CONFIG) / maxTasks;
```
My vote would be to have both per-task (get rid of the above code), and change the config to include a task prefix (taskBufferSize, and taskMaxWriteSize).

**Comment by C0urante** [comment]
The reasoning behind the
```java
int maxWritePerTask = config.getInt(config.MAX_WRITE_CONFIG) / maxTasks;
```
line was that `maxTasks` wasn't known until runtime, and as a result it seemed better to allow the user to specify `maxWriteSize` on a per-connector basis instead of a per-task basis. So, an alternative could be to replicate that line with regards to the `bufferSize` passed to each task.

I think it really boils down to a choice between configuring task-specific settings and configuring connector-specific settings. I like the idea of connector-specific better, since it allows each task to adjust its write/buffer size intelligently as the number of tasks changes.

**Comment by mtagle** [comment]
I'm going to close this since DynamicBatchWriter handles the concept of maxWriteSize differently than the old system did.
