### ISSUE TITLE
Add badges for CI and whatnot

### ISSUE THREAD

**Issue by criccomini** [wepay/kafka-connect-bigquery#17]
We should add badges for license, maven central, travis ci, code coverage, etc. Similar to DBZ's badges in their readme:

https://github.com/debezium/debezium

**Comment by C0urante** [comment]
Looks like @skyzyx's gotten started on that with https://github.com/wepay/kafka-connect-bigquery/pull/7; Ryan, would you be willing to add a badge for Maven Central to the PR?

**Comment by skyzyx** [comment]
Sure. What's the location/name?

**Comment by C0urante** [comment]
@skyzyx The Maven Central repo is [here](http://repo1.maven.org/maven2/com/wepay/kafka-connect-bigquery/0.2.1/); group ID "com.wepay", artifact ID "kafka-connect-bigquery".

**Comment by skyzyx** [comment]
This is now available in PR #9.
