### ISSUE TITLE
Issue Inserting Timestamp Type Field

### ISSUE THREAD

**Issue by archy-bold** [wepay/kafka-connect-bigquery#217]
I'm trying to insert a timestamp-type field into BigQuery. The table is already set up and the schema set.

I've tried simply inserting the bigint/long field into the timestamp field.

I've also tried converting from a date string:

```json
    "transforms": "ConvertTimestamp",
    "transforms.ConvertTimestamp.type": "org.apache.kafka.connect.transforms.TimestampConverter$Value",
    "transforms.ConvertTimestamp.field": "DATESTAMP",
    "transforms.ConvertTimestamp.target.type": "Timestamp",
    "transforms.ConvertTimestamp.format": "yyyy-MM-dd'T'HH:mm:ssXXX"
```

But I always get errors like the following:

> [row index 404]: invalid: Timestamp field value is out of range:1574731800000000000

That value is longer than the one stored in the AVRO row. Am I doing something wrong?

I'm using version 1.3.0

**Comment by archy-bold** [comment]
And if I try the following transform, to simply convert the integer field to type Timestamp with this config:

```json
    "transforms": "ConvertTimestamp",
    "transforms.ConvertTimestamp.type": "org.apache.kafka.connect.transforms.TimestampConverter$Value",
    "transforms.ConvertTimestamp.field": "TIMESTAMP",
    "transforms.ConvertTimestamp.target.type": "Timestamp"
```

I get this error:

> [2019-11-29 14:32:05,710] INFO Putting 500 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask)
> [2019-11-29 14:32:05,811] ERROR Task failed with org.apache.kafka.connect.errors.ConnectException error: Attempted to reduce batch size below 1. (com.wepay.kafka.connect.bigquery.write.batch.KCBQThreadPoolExecutor)
> [2019-11-29 14:32:05,822] INFO Putting 500 records in the sink. (com.wepay.kafka.connect.bigquery.BigQuerySinkTask)
> Exception in thread "pool-27-thread-1033" org.apache.kafka.connect.errors.ConnectException: Attempted to reduce batch size below 1.
>   at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.getNewBatchSize(TableWriter.java:110)
>   at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.run(TableWriter.java:87)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>   at java.lang.Thread.run(Thread.java:748)

I tried changing the writer with the  `batchWriter` config option but that doesn't seem to be supported any more.

**Comment by mortenberg80** [comment]
We got the same problem when we tried to store the timestamp as a long, and we fixed it by changing the type in the Avro schema:

```
 {
    "name": "timestamp",
    "type": {
      "type": "long",
      "connect.name": "org.apache.kafka.connect.data.Timestamp"
    },
    "doc": "Timestamp in millis since epoch UTC"
  }
```

We had to add the `"connect.name": "org.apache.kafka.connect.data.Timestamp"`. We just happened to stumble upon this from the tests in this project.

Does anyone know if there exists any documentation describing the Avro schema types, and their compatibility with BQ schemas?

**Comment by archy-bold** [comment]
@mortenberg80 Many thanks, I'm getting the same error as my second comment now so I'm assuming the transform and the schema type both achieve the same result of correctly converting to a timestamp.

I think the error I'm getting now is related to [this](https://github.com/wepay/kafka-connect-bigquery/issues/201) as I'm partitioning the table by that timestamp field. There look to be a few pull requests to resolve it so hopefully they'll be sorted soon.

**Comment by mortenberg80** [comment]
Regarding the `Attempted to reduce batch size below 1.`-error, I found the following commnet: https://github.com/wepay/kafka-connect-bigquery/issues/104#issuecomment-368685173
In other words, the writer is failing on all inserts.

We are partitioning on ingestion time, so that might be the problem. I didn't know that partition by field was supported yet? How do you configure that?

**Comment by archy-bold** [comment]
Thanks for the explanation of the error, it would be helpful for the error from BigQuery to be reported too so we can see what the problem actually is.

> We are partitioning on ingestion time, so that might be the problem. I didn't know that partition by field was supported yet? How do you configure that?

I just set up a table in BigQuery manually with the correct schema and partitioned at that point. I've also compiled the [source from this PR](https://github.com/wepay/kafka-connect-bigquery/pull/214) and am using that. I've not got it all working yet, though!

**Comment by archy-bold** [comment]
Ok, I finally got this working. I think `"connect.name": "org.apache.kafka.connect.data.Timestamp"` is needed on the schema to create the table initially, but once created, the schema doesn't seem to be used again.

The issue I had was that I was creating a column which used the kafka `ROWTIME` value as the timestamp, which I assume is in microseconds. Once I divided that by 1000 I was no longer getting the 'Timestamp value is out of range' error.

Annoyingly confluent seems to recognise when a long field is a timestamp and always displays it as microseconds, which caused confusion over the actual length of the timestamp value.

Thanks for your help @mortenberg80, got there in the end!

**Comment by archy-bold** [comment]
And re the `Attempted to reduce batch size below 1.` error. The issue was in the timestamp-field partitioning. It was a bug in the PR in how it inserted rows into the table. Info here: https://github.com/wepay/kafka-connect-bigquery/pull/214#issuecomment-561337346
