### ISSUE TITLE
Publishing version 1.5.1 to Confluent Hub 

### ISSUE THREAD

**Issue by nysthee** [wepay/kafka-connect-bigquery#234]
Hi 

Would it be possible to publish the latest released version to Confluent Hub?

Thanks!

**Comment by mtagle** [comment]
Hey, basically all the maintainers are on break right now but I can put in a request to see if we can cut a release in early January.

**Comment by nysthee** [comment]
Hi 

First of all Happy New Year!
Do you know when this will happen?

**Comment by nysthee** [comment]
Is this something that can happen, please?
