### ISSUE TITLE
Upgrade Confluent platform to 3.1.1 release

### ISSUE THREAD

**Issue by C0urante** [wepay/kafka-connect-bigquery#37]
Good news everyone! Confluent 3.1.1 is out!

After bumping the version, we should also include a new integration test to make sure that identical schemas with different names no longer cause issues when using the Confluent Avro Converter. However, Confluent hasn't yet released a new Docker image for the 3.1.1 release of Schema Registry (issue created [here](https://github.com/confluentinc/docker-images/issues/49)), so no integration tests (new or existing) can be run with the new version of the platform just yet. We should probably block for now on them releasing updated Docker images before updating to 3.1.1 so that we can have some kind of reliable sanity check to make sure that everything works as expected.

**Comment by criccomini** [comment]
Thanks! :)

**Comment by RaiseJohnBarry** [comment]
this one is complete
