### ISSUE TITLE
Support BigQuery partitioning in Kafka connector

### ISSUE THREAD

**Issue by criccomini** [wepay/kafka-connect-bigquery#39]
BigQuery supports YYYYMMDD partitioning tables. This feature is documented [here](https://cloud.google.com/bigquery/docs/partitioned-tables). This will be a required feature when we start loading tracking data from Kafka into BigQuery, as we'll want to time-partition it, and implement a retention policy.

It seems like we might want this always enabled, simply by [creating all tables with date partitions](https://cloud.google.com/bigquery/docs/creating-partitioned-tables) in the connector. We'll probably also want a regex-based config to be able to define if a field in the incoming message should be used as the partition date (e.g. a 'produced_ts' field).

**Comment by criccomini** [comment]
Closed by https://github.com/wepay/kafka-connect-bigquery/pull/48

**Comment by willyhoang** [comment]
Just for clarification, now that #48 is merged does this mean all tables moving forward will be data-partitioned tables? 

On a related note, what is the suggested method for handling this change when upgrading kafka-connect-bigquery? Is the best way to drop the existing tables in BigQuery and have a new BigQuery Sink connector create them and re-load messages?

**Comment by criccomini** [comment]
> Just for clarification, now that #48 is merged does this mean all tables moving forward will be data-partitioned tables?

Correct. The partitioning is based on the time that the row is inserted. One thing to be aware of is that this means that if you load a ton of data at once (e.g. loading all existing data from a Kafka topic), it'll all go into the partition for the day it's loaded. The decision to go this route was that, by writing only to the head of the table, it makes it much easier to do maintenance on past partitions (i.e. prior days). We opted to keep the BigQuery topic's behavior much like that of a Kafka topic: append to the end of the topic, so you can do compaction/repartitioning on prior days without affecting writes that might be in flight (since they're always going to the latest partition).

> Is the best way to drop the existing tables in BigQuery and have a new BigQuery Sink connector create them and re-load messages?

Yes, this is what we did. This change was backwards incompatible, so it requires rebootstrapping or manually migrating--sorry for that inconvenience.

It's technically possible to migrate from YYYYMMDD-based (old style) BigQuery partitions to the new partitioning scheme, but we opted not to do that because it was a lot more manual work.

**Comment by willyhoang** [comment]
Great, thanks @criccomini for the quick and thorough response!
