### ISSUE TITLE
Add a Google Cloud Storage BQ writer

### ISSUE THREAD

**Issue by criccomini** [wepay/kafka-connect-bigquery#64]
KCBQ streams all writes into BigQuery. This is actually less efficient when trying to bulk load data into BigQuery, compared to the GCS->BQ loading style. We should investigate adding the ability to bulk load data by writing it into a GCS bucket, and then loading it into BigQuery

This will be a bit complicated, as GCS is eventually consistent, and files that are uploaded might not (and often do not) appear for > 5 minutes after they've been uploaded. We can't block the flush() method for that long, so there might have to be two phases: 1) upload to GCS, 2) load from GCS into BQ. (2) can happen asynchronously, but must be tolerant to failures (i.e. if KCBQ is restarted, it should still load the remaining GCS files that were not yet bulk loaded into BQ).

Another thing to consider is dynamically switching back and forth depending on the KCBQ throughput (i.e. if you get more than 1 million rows in N seconds, switch to GCS/bulk load mode).

This is a long-term thing, but something to think about.

**Comment by criccomini** [comment]
This was merged in.

**Comment by darrenhaken** [comment]
@criccomini are there any docs on how to do this?

**Comment by criccomini** [comment]
Best place to look is here:

https://github.com/wepay/kafka-connect-bigquery/wiki/Connector-Configuration

There are a few GCS-specific config that you need to set.

**Comment by darrenhaken** [comment]
@criccomini thanks!
